### PR TITLE
feat(port): support Waybar

### PR DESCRIPTION
**Pull request by Hendrikto**
#### Description

This PR adds a port for [Waybar](https://github.com/Alexays/Waybar).

#### Questions

1. Should the `config` file be included? Should we link to it?
2. Waybar does not seem to have a logo. I used the profile picture of its author as a placeholder. How should we handle this?

#### Assets

1. The project does not have a logo (see question 2 above).
2. [whole screen](https://user-images.githubusercontent.com/8006842/223466235-5d665994-3f52-4b8a-b57e-8cf82b82c924.png)
   [just the bar](https://user-images.githubusercontent.com/8006842/223466463-c69ad473-ec5e-42df-bfa3-86c591fc9df4.png)

#### Checklist

- [X] PR description included
- [X] I've read the [documents](https://github.com/daltonmenezes/aura-theme#documentation)
- [X] I've created or commented in an [issue related to this port](https://github.com/daltonmenezes/aura-theme/issues/178) asking to work on it
- [X] I know I shouldn't change any files in the packages folder manually
- [X] I've added this port at the end of the related category list in the [main README](https://github.com/daltonmenezes/aura-theme/blob/main/README.md)
- [X] I've attached an image to the icon of the app that this port is related to
- [X] I've attached a screenshot with a good zoom in fullscreen showing this port in action

### CODE REVIEW

**Comment by Hendrikto** [comment]
#### RE: Question 1

I don't know how familiar you are with Waybar. A full configuration consists of two files: `config` and `style.css`.

* `config` specifies modules and their layout.
* `style.css` defines how those modules are styled.

I only included the `style.css` file in this PR, because `config` is not strictly related to theming. The `style.css` file does not directly depend on `config` or vice versa. They just go well together.

However, we might at least want to link to an [example `config`](https://github.com/Hendrikto/config_files/blob/master/waybar/config), such that the example screenshot can easily be reproduced.

**Comment by daltonmenezes** [comment]
Hi @Hendrikto , about your questions:

1. You can link the example config file and the necessary instructions for the people who never made this, what do you think about it?
2. I made a simple icon for Waybar for us:
waybar-icon

**Comment by daltonmenezes** [comment]
@Hendrikto for the banner image you can use this one:
Group 1

**Comment by Hendrikto** [comment]
Should I use 
```ts
const previewURL = `https://github.com/${info.author.username}/assets/blob/master/images/${info.slug}/aura-waybar-preview.png?raw=true`
```
?

**Comment by daltonmenezes** [comment]
> Should I use
> 
> ```ts
> const previewURL = `https://github.com/${info.author.username}/assets/blob/master/images/${info.slug}/aura-waybar-preview.png?raw=true`
> ```
> 
> ?

This one, please:
```
https://user-images.githubusercontent.com/1149845/223881256-6726819c-5ce5-4c84-a84b-0a4f70993b96.png
```

**Comment by Hendrikto** [comment]
Everything should be done now :+1:

**Review by daltonmenezes — APPROVED** [review]

**Comment by daltonmenezes** [comment]
Well done @Hendrikto , thanks 💜

**Pull request merged**
