### PR TITLE
Fix bracket and tag scope highlighting for Sublime Text

### PR DESCRIPTION
**Pull request by Hendrikto**
#### Description

Fixes issues #94 and #96.

#### Checklist

- [x] PR description included
- [x] I've read the [documents](https://github.com/daltonmenezes/aura-theme#documentation)
- [x] I've created or commented in an issue related to this port asking to work on it
- [x] I know I shouldn't change any files in the packages folder manually

### CODE REVIEW

**Comment by daltonmenezes** [comment]
Hi @Hendrikto , could you please provide a screenshot showing the result? It's important for quick feedback. 💜

**Comment by Hendrikto** [comment]
> Hi @Hendrikto , could you please provide a screenshot showing the result? It's important for quick feedback. :purple_heart:

Sure thing.

It is a bit hard to see, due to #96, but in the after image you can see that the parentheses are now underlined

**Before:**

before

**After:**

before

**Comment by daltonmenezes** [comment]
@Hendrikto perfect, thanks. How about to try it to accent1 or accent2?

**Comment by Hendrikto** [comment]
> How about to try it to accent1 or accent2?

Both work well. Personally, I think I prefer `accent2`.

*`accent1`:*

image

*`accent2`:*

image

**Comment by daltonmenezes** [comment]
@Hendrikto we can go with the **accent2** if it's perfect for you. Also, this PR can have the change from **accent17** to **accent2** without no problem, as this change makes it more visible. 😄

**Comment by Hendrikto** [comment]
Also fixes #96 now.

**Review by daltonmenezes — APPROVED** [review]

**Comment by daltonmenezes** [comment]
Thank you so much for your contribution @Hendrikto 💜

**Pull request merged**
