### PR TITLE
Alacritty deprecated YAML format for TOML

### LINKED ISSUE #204: Update alacritty package and related instructions to use TOML
While setting up Alacritty to use this beautiful theme, I received a warning about the use of the provided ```.yml``` file. As I understand it, this should be converted to the TOML format. I have made the necessary changes in my own ```~/.config/alacritty/``` directory and have confirmed that the changes I've made work properly. Therefore, I am willing to work on the issue and submit a PR, since it is a simple change.

### PR DESCRIPTION
**Pull request by MadJlzz**
Fixes #204

### CODE REVIEW

**Comment by daltonmenezes** [comment]
Hi @MadJlzz , I'm sorry for the delay. Also, we never must change any file in the packages folder manually, we always should make changes in the `src/ports` folder, then you can rebuild the alacritty port by running:
```js
yarn build only alacritty
```
please, [read the docs](https://github.com/daltonmenezes/aura-theme?tab=readme-ov-file#documentation) to make it properly and also adding yourself as a contributor in the port readme

**Comment by MadJlzz** [comment]
Sure thing @daltonmenezes ; I will check that today or this weekend

**Comment by MadJlzz** [comment]
@daltonmenezes done! Should I rebase or is that okay for you?

**Review by daltonmenezes — APPROVED** [review]

**Comment by daltonmenezes** [comment]
> @daltonmenezes done! Should I rebase or is that okay for you?

It`s okay, thank you so much @MadJlzz 💜

**Pull request merged**
