### PR TITLE
feat(port): add helix

### LINKED ISSUE #202: Helix support?
Support for the [helix editor](https://helix-editor.com/) would be awesome! I can try my hand at making the theme if you'd like.

The [theme configuration](https://docs.helix-editor.com/themes.html) looks pretty straight forward as it's mean to use terminal colors by default and uses tree-sitter grammar for configuring syntax highlighting, so large parts of other editor themes might be able to be directly recycled if they also are configured through tree-sitter.

### PR DESCRIPTION
**Pull request by elainabialkowski**
#### Description

This PR:

Adding port for helix-editor.

#### Assets

helix icon

aura

#### Checklist

- [ x] PR description included
- [ x] I've read the [documents](https://github.com/daltonmenezes/aura-theme#documentation)
- [x ] I've created or commented in an issue related to this port asking to work on it
- [ x] I know I shouldn't change any files in the packages folder manually
- [ ] I've added this port at the end of the related category list in the [main README](https://github.com/daltonmenezes/aura-theme/blob/main/README.md)
- [ x] I've attached an image to the icon of the app that this port is related to
- [x ] I've attached a screenshot with a good zoom in fullscreen showing this port in action

### CODE REVIEW

**Comment by daltonmenezes** [comment]
@elainabialkowski please, update the icon and banner to:

icon
banner

**Comment by daltonmenezes** [comment]
@elainabialkowski also, after the requested update, you must run the build by running:
```bash
yarn build only helix
```
and push the result to this PR

**Comment by elainabialkowski** [comment]
Would you like me to store the images in the repository next to the implementation itself?

**Comment by daltonmenezes** [comment]
> Would you like me to store the images in the repository next to the implementation itself?

No, you can just copy the image links and use it as it is

**Comment by diceeth** [comment]
any updates? cant wait to use it

**Comment by rahil627** [comment]
```
$ yarn aura make
$ yarn tsnd src/core/cli/aura.ts make
$ tsnd -r tsconfig-paths/register --transpile-only --ignore-watch node_modules src/core/cli/aura.ts make
'tsnd' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
welp, i tried. lol... now to delete anything javascript 😰 

..but i see why the person gave up. this is over-engineering to the max, of the worst flavor 😭

**Comment by rahil627** [comment]
oooh i see, have to run `yarn` once to install. hooooooly shit at 750 deps?? abort!!!!! lmao.

**Comment by ionztorm** [comment]
oh no I was looking forward to this one!

**Comment by rahil627** [comment]
https://github.com/helix-editor/helix/pull/11791
  - looks like it was merged on 7/26

**Pull request closed without merging**
