### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HorebParraud**
CleanShot 2021-09-15 at 12 08 31

### CODE REVIEW

**Comment by daltonmenezes** [comment]
Hi @HorebParraud , unfortunately I won't be able to accept your PR, one of the reasons is that removes the CTRL + F search ability by the name of the app and for the 2.0v of Aura the list of ports is growing.

**Comment by HorebParraud** [comment]
Would you mind if I tried to make the CTRL+F work?
I would love to contribute in some way so if you need anything else let me know :)

**Comment by daltonmenezes** [comment]
Hi @HorebParraud 

The README will change as you can see here
Captura de Tela 2021-09-16 às 21 54 39

I really appreciate your help, I'm working now on v2.0 and for sure you can help when v2.0 was released. I'm working from the scratch to make the port creation easier and all help will be very welcome. Thanks 💜

**Comment by HorebParraud** [comment]
ok great don't hesitate to ping me ;)

**Pull request closed without merging**
