### PR TITLE
feat(port): Add port to BetterDiscord

### PR DESCRIPTION
**Pull request by eulixir**
#### Description

This PR has a objective to add a Discord port to aura.

Issue: [#164](https://github.com/daltonmenezes/aura-theme/issues/164)

Topic: [#111](https://github.com/daltonmenezes/aura-theme/discussions/111)

##### Logo 
discord

##### Preview
discord-screen

#### Checklist

- [X] PR description included
- [X] I've read the [documents](https://github.com/daltonmenezes/aura-theme#documentation)
- [X] I've created or commented in an issue related to this port asking to work on it
- [x] I know I shouldn't change any files in the packages folder manually
- [x] I've added this port at the end of the related category list in the [main README](https://github.com/daltonmenezes/aura-theme/blob/main/README.md)
- [x] I've attached an image to the icon of the app that this port is related to
- [x] I've attached a screenshot with a good zoom in fullscreen showing this port in action

### CODE REVIEW

**Comment by reoccurcat** [comment]
After applying the css you uploaded to my Discord client, it looks pretty good so far! Excited for this to make it to master eventually

**Comment by joaopealves** [comment]
discord
discord-screen

**Comment by reoccurcat** [comment]
The two things I see that are out of style are the bar that is on the side of a DM showing the profile info:
image
and the actual profile:
image

**Comment by joaopealves** [comment]
@reoccurcat Thanks for feedback!!

I'm not sure this is a feature of Better Discord or anything related to the theme. 

I'll take a look at it calmly! :)

**Comment by reoccurcat** [comment]
It should be possible editing the CSS for the background colors of the profile things so that they are in the color scheme as well but yeah thank you!

**Comment by daltonmenezes** [comment]
@joaopealves  please, sync your branch with latest repo changes from main and update the icon and banner to:

icon

banner

**Comment by eulixir** [comment]
Hey @daltonmenezes, can you check again?

**Comment by daltonmenezes** [comment]
@eulixir the css file was not compiled to the packages folder and you should also avoid using hard-coded colors you should use the aura tokens please

**Comment by daltonmenezes** [comment]
@eulixir I think we should rename the port and related folders to `better-discord` instead of `discord`

**Pull request closed without merging**
