### PR TITLE
Kitty terminal port

### LINKED ISSUE #41: Port for Kitty terminal
I use Kitty terminal and Fish shell. I'm working on the Fish shell port so I was thinking I might work on a Kitty port as well.

### PR DESCRIPTION
**Pull request by FelipeRosa**
Closes #41.

### CODE REVIEW

**Comment by FelipeRosa** [comment]
> Hi @FelipeRosa I made the initial review, also I need you edit the PR text and add the app icon (it can be a URL) and the full-screen screenshot preview with the theme in action purple_heart

Ok! PR text changed. 

Also I added installation steps on README.md and changed the contributors section as you mentioned in #38.

I'll get the app icon and take the preview screenshot.

**Comment by FelipeRosa** [comment]
Does this look good?

image

**Comment by FelipeRosa** [comment]
Also Kitty's app icon: https://sw.kovidgoyal.net/kitty/_static/kitty.svg

Do you need it in any specific image format?

**Comment by daltonmenezes** [comment]
@FelipeRosa the port looks perfect, well done 💜
About the screenshot, could you please take one with a good zoom on the terminal like [this one](https://raw.githubusercontent.com/daltonmenezes/assets/master/images/aura-theme/aura-hyper-preview.png)?

**Comment by daltonmenezes** [comment]
Hi @FelipeRosa , only the 2 changes that I requested in the review I did yesterday are missing. After that I will review it again locally to see if everything is ok and I believe I can merge your PR. 🚀

**Comment by FelipeRosa** [comment]
Hey @daltonmenezes, I made those changes on my lastest commit. Forgot to mention.

**Comment by daltonmenezes** [comment]
@FelipeRosa it's still pending 🤔
Captura de Tela 2021-10-07 às 20 15 38

**Comment by FelipeRosa** [comment]
@daltonmenezes I believe you have to finish the review to confirm the comments. They won't appear to me if you don't.

**Comment by daltonmenezes** [comment]
Thank you so much @FelipeRosa , great addition. Congrats 💜

**Pull request merged**
